#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : py2cairo
Version  : 1.10.0
Release  : 1
URL      : https://www.cairographics.org/releases/py2cairo-1.10.0.tar.bz2
Source0  : https://www.cairographics.org/releases/py2cairo-1.10.0.tar.bz2
Summary  : Python bindings for cairo
Group    : Development/Tools
License  : LGPL-2.1 MPL-1.1
BuildRequires : pkgconfig(cairo)

%description
Pycairo - Python bindings for cairo
http://www.cairographics.org/pycairo
Dependencies
------------
cairo   >= 1.10.0
Python  >= 2.6


%files
%defattr(-,root,root,-)
